### ISSUE TITLE
Update JWT implementation

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-hub#54]
Discussion issue for resolving some security issues in the current implementation.

Diagram below is a high-level representation of the current architecture:

![hub_sequence](https://user-images.githubusercontent.com/43223637/103260234-d42be000-4a01-11eb-9a9d-52bd882c6b93.png)

Notes:

- The init JWT is hardcoded into the mSupply source code.
- JWT tokens are signed using a passphrase stored in a config file on the server.

A few issues with this:

- If the init token is compromised, this requires patching mSupply and making the choice of either forcing all clients to update or breaking existing deployments.
- The init token needs to be sent over a secure connection, so why not just use credentials?
- The site token is persisted as an indefinite "session", without any mechanism for expiring. 
- There is no client-server verification to ensure the client is sending data to a trusted hub (vulnerable to e.g. DNS spoofing).

Proposed implementation:

- To setup an mSupply instance with the hub, credentials are entered by the admin/user and verified by the hub server. If the credentials are valid, the server responds with a JWT (claims to be decided, but could include permissions, expiry etc.). The credentials can be on a per-deployment basis, per-organisation basis, or a master password used for all deployments. 
- The hub server is registered with a keypair: allows client to verify the hub server and the server to sign/verify the JWT.
- JWT tokens include an expiry claim and are refreshed on each use (client POSTs event data with JWT, server validates and updates database, server responds with new JWT). If a site does not communicate for an extended period of time, its token expires and it must re-register with credentials to get a valid token. 
- Optional: note that this still doesn't solve the problem of revoking individual tokens. Could add a table or simple key-value store for the server to maintain a whitelist of issued tokens IDs?

@mark-prins @nmadruga Any thoughts?

**Comment by nmadruga** [comment]
## Proposed implementation 1

> To setup an mSupply instance with the hub, credentials are entered by the admin/user and verified by the hub server. If the credentials are valid, the server responds with a JWT (claims to be decided, but could include permissions, expiry etc.). The credentials can be on a per-deployment basis, per-organisation basis, or a master password used for all deployments.

I like this idea and the whole security changes proposed. Although I think the intention was to allow mSupply to start the connection to the Hub automatically (in the next iterations) and have each site registration working from the Info Hub. Adding the step to enter credentials by the admin/user would require in every installation someone to "start the push". Or will this be considering the those credentials would be stored in the site database when the released version was created?

**Comment by nmadruga** [comment]
## Proposed implementation 2

> The hub server is registered with a keypair: allows client to verify the hub server and the server to sign/verify the JWT.

Great idea! Just one question: when is this keypair generated? Do we need to store it in each instance of mSupply server and if the keypair changes how do we update?

**Comment by nmadruga** [comment]
## Proposed implementation 3

> JWT tokens include an expiry claim and are refreshed on each use (client POSTs event data with JWT, server validates and updates database, server responds with new JWT). If a site does not communicate for an extended period of time, its token expires and it must re-register with credentials to get a valid token.

I think this idea is clashing with the one you included on the issue #55:

> Since JWT is stateless, do we need to store it in the DB? Can't we use it statelessly by validating/regenerating on the fly?

The idea on #55 seems to be not to store the JWT token in the database and the idea here would be to store and use an expiry date on it. I think I like more the idea on #55, because with expirying what would happen if the site gets **shutdown** for a period longer than the expiry of the token? That's something that happens some times with mSupply servers (for various reasons). With this solution  would the Admin have to intersept the problem and login again to fix?

**Comment by wlthomson** [comment]
> 
> ## Proposed implementation 1
> 
> > To setup an mSupply instance with the hub, credentials are entered by the admin/user and verified by the hub server. If the credentials are valid, the server responds with a JWT (claims to be decided, but could include permissions, expiry etc.). The credentials can be on a per-deployment basis, per-organisation basis, or a master password used for all deployments.
> 
> I like this idea and the whole security changes proposed. Although I think the intention was to allow mSupply to start the connection to the Hub automatically (in the next iterations) and have each site registration working from the Info Hub. Adding the step to enter credentials by the admin/user would require in every installation someone to "start the push". Or will this be considering the those credentials would be stored in the site database when the released version was created?

Credentials should only need to be entered once (or on JWT expiry). After entering credentials, the server will reply with a JWT. If the client uses that JWT within the expiry period, they'll get a new one, and so on. The only time credentials will need to be re-enetered is if the client doesn't push for a given amount of time. Does that make sense?

**Comment by wlthomson** [comment]
> 
> ## Proposed implementation 2
> 
> > The hub server is registered with a keypair: allows client to verify the hub server and the server to sign/verify the JWT.
> 
> Great idea! Just one question: when is this keypair generated? Do we need to store it in each instance of mSupply server and if the keypair changes how do we update?

Keypair would only need to be stored on the hub server (mSupply would need to know the public key, so this might need to be stored somewhere on the mSupply server, which is the weak point of the implementation, but unavoidable!).

**Comment by wlthomson** [comment]
> 
> ## Proposed implementation 3
> 
> > JWT tokens include an expiry claim and are refreshed on each use (client POSTs event data with JWT, server validates and updates database, server responds with new JWT). If a site does not communicate for an extended period of time, its token expires and it must re-register with credentials to get a valid token.
> 
> I think this idea is clashing with the one you included on the issue #55:

I don't think so? I think it still works? Why do you think it clashes?

> > Since JWT is stateless, do we need to store it in the DB? Can't we use it statelessly by validating/regenerating on the fly?
> 
> The idea on #55 seems to be not to store the JWT token in the database and the idea here would be to store and use an expiry date on it.

The expiry date would be a claim on the JWT (the JWT would be stored on the mSupply database, but not the hub database, and would be one use only).

> I think I like more the idea on #55, because with expirying what would happen if the site gets **shutdown** for a period longer than the expiry of the token? That's something that happens some times with mSupply servers (for various reasons). With this solution would the Admin have to intersept the problem and login again to fix?
 
 That's correct. We'd have to setup an expiry duration which we think is reasonable to handle these situations!

**Comment by wlthomson** [comment]
@nmadruga Note also that by using credentials there is no longer a differentiation between "types" of JWT... so we can remove that claim from the JWT too!

**Comment by nmadruga** [comment]
## Proposed implementation 1

continuing...

> Credentials should only need to be entered once (or on JWT expiry). After entering credentials, the server will reply with a JWT. If the client uses that JWT within the expiry period, they'll get a new one, and so on. The only time credentials will need to be re-enetered is if the client doesn't push for a given amount of time. Does that make sense?

Yes. But as stated [here](https://github.com/openmsupply/msupply-hub/issues/55#issuecomment-752758318), I think we need some mechanisms to allow a already authorised site to continue to push to the Info Hub server by re-entering some credentials (probably storing these on the DB of mSupply after initial setup).

**Comment by nmadruga** [comment]
## Proposed implementation 2

continuing...

> Keypair would only need to be stored on the hub server (mSupply would need to know the public key, so this might need to be stored somewhere on the mSupply server, which is the weak point of the implementation, but unavoidable!).

Cool. But I was asking IF we need to regenerate this keypair. What is the plan for fixing that on each mSupply site?

**Comment by nmadruga** [comment]
## Proposed implementation 3

> The expiry date would be a claim on the JWT (the JWT would be stored on the mSupply database, but not the hub database, and would be one use only). To clarify, #55 is suggesting not storing the JWT in the hub DB, would still need to store it in the mSupply DB (but since it has an expiry claim it in, the one stored mSupply side would only be valid for a certain duration, hence why a new one is issued every time an existing one is used to push an event).

Thanks for the explanation. It was clear to me before, so storing only in mSupply and validating (and regenerate) on the Info Hub server. I have a few question about this re-generation [here](https://github.com/openmsupply/msupply-hub/issues/55#issuecomment-752758318).

>  That's correct. We'd have to setup an expiry duration which we think is reasonable to handle these situations!

Also how long do you suggest? Like a week or a few days?

**Comment by nmadruga** [comment]
> Note also that by using credentials there is no longer a differentiation between "types" of JWT... so we can remove that claim from the JWT too!

This is super cool. : )

**Comment by nmadruga** [comment]
What I'm thinking here is that ideally in the future we would allow a new site to get connected to the Info Hub automatically (by checking a box) and use this connection to register the site from our end (in the Info Hub). This could help with local support staff to be able to create and push the site in a single step without much intervention from us. 

We can start by setting this credentials on the initial setup, but I think we need to aim a solution that doesn't require this step one day. This is why I was using that initial JWT token. Although I agree with you that it needs to have an expiry date and some way to fix a compromised initial token.

**Comment by wlthomson** [comment]
> 
> 
> What I'm thinking here is that ideally in the future we would allow a new site to get connected to the Info Hub automatically (by checking a box) and use this connection to register the site from our end (in the Info Hub). Helping any local support staff to be able to create a site that already push to the Info Hub in a single step without much intervention from us.
> 
> We can start by setting this credentials on the initial setup, but I think we need to aim a solution that doesn't require this step one day. This is why I was using that initial JWT token. Although I agree with you that it needs to have an expiry date and some way to fix a compromised initial token.

I think this requirement is pretty much impossible without storing credentials in persistent storage (which is a security vulnerability and would require updating mSupply if anything goes wrong). I'm personally pretty strongly against this... I think manual intervention (or some sort of individualised credentials system where we give local staff their own hub credentials to store safely) is pretty much a necessity and would end up being a lot less headache and a lot less risky!

**Comment by wlthomson** [comment]
> 
> ## Proposed implementation 2
> 
> continuing...
> 
> > Keypair would only need to be stored on the hub server (mSupply would need to know the public key, so this might need to be stored somewhere on the mSupply server, which is the weak point of the implementation, but unavoidable!).
> 
> Cool. But I was asking IF we need to regenerate this keypair. What is the plan for fixing that on each mSupply site?

If the keypair is compromised, we would have big problems. This should never happen! Luckily keypairs are more secure than credentials (i.e. can't be brute forced, rainbow attacked), so this should still be a lot more secure. However, if it did happen, we would have to update mSupply urgently. I think this is probably also unavoidable. It might be possible to use a registry to get the public key (rather than hardcode it directly), which would allow us to replace the public key in the registry without needing to update mSupply (but I'm not sure of the details of this).

**Comment by wlthomson** [comment]
I'm going to close this as I think this is superseded by future discussion!
