### ISSUE TITLE
Update table schema

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-hub#55]
Diagram below represents current DB schema:

![hub_table_v1](https://user-images.githubusercontent.com/43223637/103272620-3c8ab980-4a22-11eb-88c0-a3637a2a58e4.png)

Questions:

- Not sure of the logic for having `data` on the `sites` table? Can the latest `data` just be taken from `events` with the latest timestamp and matching UUID?
- What is the difference between `created` and `triggered` on the`events` table?
- Since JWT is stateless, do we need to store it in the DB? Can't we use it statelessly by validating/regenerating on the fly? 

Proposed changes:

- Use singular table names: `site`, `event`, etc.
- Simplify schema by removing duplicate `data` fields (can index event timestamps if needed)?
- Do not persist JWTs in storage.
- Rename `UUID`, `machineUUID`, `siteUUID` to `id`,`machineId` and `siteId` for simplicity (I don't think there is any removal of confusion by naming the field explicitly as a UUID, so may as well make it a bit tidier?).
- Add `siteGroup` table for grouping sites (e.g. by organisation).

@nmadruga @mark-prins Any thoughts?

**Comment by nmadruga** [comment]
Trying to answer some of the questions to continue the debate here : )

> Not sure of the logic for having data on the sites table? Can the latest data just be taken from events with the latest timestamp and matching UUID?

Not sure either. I think the original idea was that some data (that would be dynamic - that's why on a json field) would only be sent once: e.g. country or project, phase, etc. After many iterations we realise that this data wouldn't be coming from mSupply, so the data field seems unneeded right now. Like you said, we can get the latest info from the events table.

**Comment by nmadruga** [comment]
> What is the difference between created and triggered on the events table?

The difference between when it happened and when it was pushed from mSupply. So `triggered` when the event/error actually happened in mSupply and `created` is the date when the event was added to the Info hub server.  
That was in use before, when we were using logs to store events and errors before sending to the Hub server, which is not the case anymore. The need was, for example, to know the exact moment when an error was `triggered` in mSupply, since it is important to know the moment when an **error** happened. Or, for events like **server shutdown**.

**Comment by nmadruga** [comment]
> Since JWT is stateless, do we need to store it in the DB? Can't we use it statelessly by validating/regenerating on the fly?

I don't know if I understood your suggestion correctly. Are you proposing to generate a **new** JWT token for each site every time the site connects (e.g. every day) then it gets the **new** JWT token to be used in the **event** push?

**Comment by nmadruga** [comment]
Proposed changes:

> Use singular table names: site, event, etc.

Agree!

> Simplify schema by removing duplicate data fields (can index event timestamps if needed)?

Yes. I think it is not needed anymore know that we know more about the **static** data for each site (and where it's going to be stored, for example, using metadata table).

> Do not persist JWTs in storage.

Need to continue on the loop for this one.

> Rename UUID, machineUUID, siteUUID to id,machineId and siteId for simplicity (I don't think there is any removal of confusion by naming the field explicitly as a UUID, so may as well make it a bit tidier?).

Yes. No problem with that.

> Add siteGroup table for grouping sites (e.g. by organisation).

Yes, I think that would be good. Should we explore better this idea on another issue? How would the organisation be defined in the Info hub?

**Comment by wlthomson** [comment]
@nmadruga All sounds good!

Re. the JWT:

For simplicity, I'll just use the existing implementation to explain. Currently, the site JWT is stored by mSupply in the DB and also by the hub in its DB.  I don't think the hub needs to store anything, as all it needs to do is regenerate or validate the JWT, both of which it can do without actually storing anything (to validate it just needs to check the signature is valid, and to regenerate it just needs to create a new JWT). Am I missing something?

**Comment by wlthomson** [comment]
> 
> ## Question 3
> 
> > Since JWT is stateless, do we need to store it in the DB? Can't we use it statelessly by validating/regenerating on the fly?
> 
> I don't know if I understood your suggestion correctly. Are you proposing to generate a **new** JWT token for each site every time the site connects (e.g. every day) then it gets the **new** JWT token to be used in the **event** push?

Not quite, but close.

1. Site gives credentials, gets JWT (with expiry claim in it). Stores JWT in DB.
2. Site pushes event using JWT. JWT hasn't expired yet. Hub validates and accepts push. Hub responds with 200 OK and a new JWT with a later expiry date.

Note that the hub never needs to store the JWT, it only needs to validate existing ones and generate new ones (neither of which require storing a record of JWTs it has issued).

**Comment by wlthomson** [comment]
@nmadruga Note that the idea of this is to avoid proliferation of valid tokens by guaranteeing that tokens older than a certain time will not work. The trade-off is that sites with a long down-time will need to have credentials re-entered, but I think that's better than having indefinitely valid tokens!

**Comment by wlthomson** [comment]
@nmadruga Note also that by using credentials there is no longer a differentiation between "types" of JWT... so we can remove that field too!

**Comment by wlthomson** [comment]
@nmadruga Thought of another thing. The `sites` table currently has a field called `updated`. I assume this is to track when the `machineId` was last updated? I think this is metadata which the DB will track internally if we need it... OK with getting rid of this field too?

**Comment by wlthomson** [comment]
@nmadruga Last thing!

Do you know the purpose of the line at the top of `initialiseDatabase.sql`: `DROP TABLE IF EXISTS "version";`?

**Comment by nmadruga** [comment]
## Question 3

...continuing

> 1. Site gives credentials, gets JWT (with expiry claim in it). Stores JWT in DB.
> 2. Site pushes event using JWT. JWT hasn't expired yet. Hub validates and accepts push. Hub responds with 200 OK and a new JWT with a later expiry date.

Yes, understood now. That's really good. We probably need to also have warning on the Info Hub server about a site that lost its connection and needs attention. Some sites can be manually disabled - which shouldn't show on the report. In my initial thought I was thinking to send which problem happened when trying to push, so we would be able to know from the hub. For example a server shutdown would send that when it was back online. Now with this approach, it would probably loose the expiry for the JWT and this information needs to be available: either logged in the Hub server as failed attempt or a report that say which sites haven't pushed lately.

**Comment by nmadruga** [comment]
> Note that the hub never needs to store the JWT, it only needs to validate existing ones and generate new ones (neither of which require storing a record of JWTs it has issued).

That's nice. And what is the dynamic variable to change the current valid JWT: 
- A secret that is changed periodically?
- Would all sites have the same expiry date for current JWT (considering we use the same secret to generate all tokens)?

**Comment by nmadruga** [comment]
> EDIT: could probably also speed this up by allowing events to be pushed with credentials as well as JWTs (i.e. instead of having to re-register the site with credentials to get a new JWT first, just send with credentials to push the event and get a new JWT for future pushes, all in one POST), but it's a minor optimisation which isn;t worth much and would probably be confusing!

Yea, it seems to be more confusing this way. I like the previously proposed solution better. We just need to consider:
- Report to know which sites have **lost connection** to the Info Hub server
- Automatic restore of site connection to the Info Hub server (storing credentials on DB and running a scheduler ?)

**Comment by nmadruga** [comment]
> Thought of another thing. The sites table currently has a field called `updated`. I assume this is to track when the machineId was last updated? I think this is metadata which the DB will track internally if we need it... OK with getting rid of this field too?

> EDIT: now I think of it... this is probably the case for `created` too!

Yes, you can remove the `updated` if you would like. I was using it to store when was the last time this site was updated, so it would get another date after receiving an event from that site.

The `created` on the event table can go, so you would only keep the `triggered` which is when the event was sent from mSupply? Is good that this will keep the local time of the server which can be handy if we start sending **errors** in the future. Just a note: need to check that we are still setting the `triggered` time on the mSupply `event` push.

**Comment by nmadruga** [comment]
> Do you know the purpose of the line at the top of initialiseDatabase.sql: DROP TABLE IF EXISTS "version";?

I think that's an automatic line when you export a dump file from some SQL managers. Not sure exactly why.

**Comment by wlthomson** [comment]
> Report to know which sites have lost connection to the Info Hub server

I think by definition this isn't really possible... if the site loses a connection then it can't communicate? The hub will have the last event sent by the site, but I think knowing when the site actually goes down isn't really possible without actively pinging it (which would make the communication bidirectional, requiring an mSupply endpoint). 

> Automatic restore of site connection to the Info Hub server (storing credentials on DB and running a scheduler ?)

I think this is another problematic requirement that doesn't have a solution without a compromise (or compromising security pretty significantly). I think the only way of solving this is with an expiry token and manual intervention. Any storing of JWT or credentials in the mSupply DB long term is a pretty massive security vulnerability IMO! The whole point of the credentials + temporary JWT is to minimise persistent storage of anything security critical. I think the balance is getting an expiry duration which is reasonable.

**Comment by wlthomson** [comment]
> 
> 
> > Thought of another thing. The sites table currently has a field called `updated`. I assume this is to track when the machineId was last updated? I think this is metadata which the DB will track internally if we need it... OK with getting rid of this field too?
> 
> > EDIT: now I think of it... this is probably the case for `created` too!
> 
> Yes, you can remove the `updated` if you would like. I was using it to store when was the last time this site was updated, so it would get another date after receiving an event from that site.
> 
> The `created` on the event table can go, so you would only keep the `triggered` which is when the event was sent from mSupply? Is good that this will keep the local time of the server which can be handy if we start sending **errors** in the future. Just a note: need to check that we are still setting the `triggered` time on the mSupply `event` push.

Yup, sounds good.

**Comment by wlthomson** [comment]
> 
> 
> > Do you know the purpose of the line at the top of initialiseDatabase.sql: DROP TABLE IF EXISTS "version";?
> 
> I think that's an automatic line when you export a dump file from some SQL managers. Not sure exactly why.

OK, will remove!

**Comment by wlthomson** [comment]
@nmadruga Another question! Do you know what the `tags` are on events? Is this logic still needed?

**Comment by nmadruga** [comment]
`tags` on events? Where you saw this, is not in the current database file or in the description of this. I think we had an idea to group sites using tags, but I don't think we have any implementation around that idea yet.

**Comment by wlthomson** [comment]
> 
> 
> `tags` on events? Where you saw this, is not in the current database file or in the description of this. I think we had an idea to group sites using tags, but I don't think we have any implementation around that idea yet.

OK, there was a bit of code around fetching "tags" from events. I'll remove it for now, can always add it back if we find out it's something we want!

**Comment by mark-prins** [comment]
nice to have the JWT stateless and the other changes sound good to me.

I think the field name `triggered` is likely because the event in mSupply is run from a trigger and that as a descriptor it isn't an ideal choice. Better to have `created` or `event_date` or `raised` - minor quibble now, if the two date fields are reduced to one

**Comment by wlthomson** [comment]
Some of this already covered by #62, but a few changes still needed:

- Use `snake_case` for table/column names (simplifies SQL queries).
- Update `triggered` to `timestamp` and remove `created` column.
