### ISSUE TITLE
Update response format

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-hub#59]
The current response format has the following shape:

```
{
  authorized: boolean,
  message: string,
  token?: object,
  result?: object
}
```

A few thoughts:

- `authorized` is covered by the HTTP status code (e.g. `200` vs. `401`).
- `message` is only really needed for errors (and can be replaced by a human-readable error code).
- `result` is unnecessarily generic, the code to handle responses has to be written on a per-request basis, so there's not much benefit here (maybe if the service scales to a lot of different entities, but I don't think that's likely?).

Suggested response format:

```
{
  error?: string,
  site?: object,
  event?: object,
  sites?: object[],
  events?: object[],
}
```

I think this should cover all the use cases, and is a bit more simple to follow. If the response is to a `POST`, then reply with the updated entity. 

E.g. if a user adds a new site `{ sideId: 'abc123', machineId: 'xyz321' }` successfully:

```
200 OK

{
  site: { siteId: 'abc123', machineId: 'xyz321' }
}
```

E.g. if a user adds a site unsuccessfully:

```
403 Forbidden

{
  error: 'CLIENT_REGISTER_EXISTING_SITE',
}
```

E.g. if user attempts to add a site with incorrect JWT:

```
{
  error:  'CLIENT_INVALID_JWT_TOKEN'
}
```

@nmadruga Thoughts?

**Comment by wlthomson** [comment]
Update:

1. Have decided to go with the approach of storing the credentials in mSupply. It's relatively secure as a hash, and if we do it on a per deployment basis, it shouldn't be an issue. This means the JWT token only needs to be returned on initial auth (no "refreshing").
2. JWT token can be returned as a `Set-Cookie` header, rather than in the body.

**Comment by nmadruga** [comment]
@wlthomson I like the change to return the error or the actual result. That's good. I don't really see a use for `sites` return though. What was the idea you thought?

Also I think your latest comment is related to a different issue.

**Comment by wlthomson** [comment]
@nmadruga Oops, you're right that previous comment was for a different issue!

This is all mostly implemented now (apart from a minor nice-to-have of returning the JWT using `Set-Cookie` header), so going to go ahead and close!
