### ISSUE TITLE
Replace JWT with basic auth

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-hub#64]
Replace JWT with basic authorisation:

- Each request contains `authorization` header.
- Basic authorisation using `Bearer Base64(rego:secret)`.

**Comment by wlthomson** [comment]
![hub_1 1](https://user-images.githubusercontent.com/43223637/104248911-45be6080-54cf-11eb-8e46-192654d665f6.png)

**Comment by andreievg** [comment]
Summary of our conversation from yesterday (from my end):

It seems like the reason for going away from already implemented JWT mechanism is security concerns. I wasn't convinced that the proposed solution offers more security.

Either way some sort of secret needs to be ether hard coded or entered to prevent non mSupply (malicious) queries from unknown sources. To me it seems safer and easier to hard code either JWT or secret (entering secret would mean sharing it, so imo less safe).

With proposed way, if site becomes unregistered, does it just disappears from hub's 'radar' so to speak ? (I am not 100% certain, but I think when hardware ID changes, registration is wiped in mSupply). I would have thought we still allow it to talk to hub, and record that it's unregistered. Might be wrong here.

`main point` -> I am happy with the proposed way to be honest. My only concern was, why we would change from already implemented way which seems to fulfil current requirements and can be extended to fulfil future requirements (with just extension and no refactor)

**Comment by wlthomson** [comment]
> It seems like the reason for going away from already implemented JWT mechanism is security concerns. I wasn't convinced that the proposed solution offers more security.

I think you're correct that this and the JWT implementation are roughly equivalent in terms of security. I think this approach offers a little bit more simplicity. I think with benefit of hindsight I would stick with the JWT (just because it was already implemented), but since I've already gone down this road, I'd propose going with this implementation just for the simplicity.

> Either way some sort of secret needs to be ether hard coded or entered to prevent non mSupply (malicious) queries from unknown sources. To me it seems safer and easier to hard code either JWT or secret (entering secret would mean sharing it, so imo less safe).

I agree with hardcoding the secret at this stage. It might be something we want to revisit, i.e. perhaps giving different sites/groups of sites individual credentials (but acknowledge the point that sharing credentials does add the possibility of human error).

> With proposed way, if site becomes unregistered, does it just disappears from hub's 'radar' so to speak ? (I am not 100% certain, but I think when hardware ID changes, registration is wiped in mSupply). I would have thought we still allow it to talk to hub, and record that it's unregistered. Might be wrong here.

That's a good point. Since the site will have the secret, we could add an endpoint, e.g `unregister` (which wouldn't require the rego, just the `siteId`). 

> main point -> I am happy with the proposed way to be honest. My only concern was, why we would change from already implemented way which seems to fulfil current requirements and can be extended to fulfil future requirements (with just extension and no refactor)

I think a valid concern, and possibly my fault for not involving you in the discussions earlier. A good reminder to share architecture discussions with all stakeholders before moving forward. Since you're ok with this way, I'll go ahead with it. Will @ you in future issues regarding architecture decisions, also.

**Comment by andreievg** [comment]
> I think a valid concern, and possibly my fault for not involving you in the discussions earlier. A good reminder to share architecture discussions with all stakeholders before moving forward. Since you're ok with this way, I'll go ahead with it. Will @ you in future issues regarding architecture decisions, also.

👍 

> I think you're correct that this and the JWT implementation are roughly equivalent in terms of security. I think this approach offers a little bit more simplicity. I think with benefit of hindsight I would stick with the JWT (just because it was already implemented), but since I've already gone down this road, I'd propose going with this implementation just for the simplicity.

I don't really want to press further on this, but also don't want misunderstanding. I am under the impression that JWT is much simpler. I guess we can compare lines of code and size of schema between JWT way and this new way to really know. (i.e. on mSupply end storing JWT that you get and using it in further queries is def simpler then compiling authorisation header from multiple prefs in DB, and on server end, just validating JWT (npm package exists) and using it's content is simpler then parsing authorisation header then looking up values in DB)

**Comment by Chris-Petty** [comment]
`Bearer: Base64(siteId:rego)` I presume is safe, given siteID being a hash based UUID?

On unregistered path, to make a rego code that's valid in mSupply you'll either need to provide hub more details (Org name, MAC, number of users...) or change how mSupply generates/checks rego (Which may well break existing instances and the current online registration portal). You'll have to check all the side affects either way. e.g. If number of users is changed on mSupply I think it's generated rego will change, and so the saved rego will then fail?

At any rate, if `register/` doesn't send anything more it's going to be nigh impossible to know what customer it is without send some more details, surely? I'd have though minimum would be `org name` and `site name`? This is going by my presumption that a sussoler should do some admin and "approve" a new site (and assign to a customer), which is lacking from the `register/` diagram.

Side note: Sometimes sites are taken down. Is there going to be a way to know this on the infoHub (i.e. for billing purposes)?

> Main question to be resolved is how to store the client-side secret:
> 
> 1. Client certificate encoded into all mSupply instances.
> 2. Hardcoded global credential.
> 3. Inject global credential into datafiles (hard to do without hardcoding into update code?).

If it's a global credential I guess just hardcode it. Though using a pref might be more future proof (even if still hardcoded) as we could adapt it for site credential later if deemed necessary.

Speaking of secrets, should this repo be public? 

@andreievg I don't know the current code so much. From what I know previously the current/old approach had a hardcoded JWT and the infoHub check against its internally identically hardcoded JWT. For lack of a traditional sort of login/ or register/ end points seems equivalent though.

**Comment by wlthomson** [comment]
> 
> 
> > I think a valid concern, and possibly my fault for not involving you in the discussions earlier. A good reminder to share architecture discussions with all stakeholders before moving forward. Since you're ok with this way, I'll go ahead with it. Will @ you in future issues regarding architecture decisions, also.
> 
> 👍
> 
> > I think you're correct that this and the JWT implementation are roughly equivalent in terms of security. I think this approach offers a little bit more simplicity. I think with benefit of hindsight I would stick with the JWT (just because it was already implemented), but since I've already gone down this road, I'd propose going with this implementation just for the simplicity.
> 
> I don't really want to press further on this, but also don't want misunderstanding. I am under the impression that JWT is much simpler. I guess we can compare lines of code and size of schema between JWT way and this new way to really know. (i.e. on mSupply end storing JWT that you get and using it in further queries is def simpler then compiling authorisation header from multiple prefs in DB, and on server end, just validating JWT (npm package exists) and using it's content is simpler then parsing authorisation header then looking up values in DB)

No worries. I think when I say simpler, I don't mean lower code complexity, I just mean simpler to grasp. I agree with the JWT approach if it's not persisted (i.e. session tokens), but with persisting the tokens you can get into a bit of trouble with the lack of ability to expire a token. Credentials are a bit more flexible in that you only need to store a single password and all the data is kept server-side only (as opposed to a signed JWT which optimises access to data already stored in the DB).

Like I said, I'm quite happy to go with JWT approach, but I think my only caveat would be replacing the "init" JWT with a secret (basically equivalent, but a bit tidier, also removes the need for differentiating different "types" of JWT).

**Comment by wlthomson** [comment]
> 
> 
> `Bearer: Base64(siteId:rego)` I presume is safe, given siteID being a hash based UUID?
> 
> On unregistered path, to make a rego code that's valid in mSupply you'll either need to provide hub more details (Org name, MAC, number of users...) or change how mSupply generates/checks rego (Which may well break existing instances and the current online registration portal). 

I think this is getting into realm of v2, but yeah, the idea was to send all the data that mSupply uses to the hub (this data is already pushed to the hub anyway, so its conceptually consistent). 

> You'll have to check all the side affects either way. e.g. If number of users is changed on mSupply I think it's generated rego will change, and so the saved rego will then fail?

That would require a reregistration, which I think can be done by sending over the old rego code with a request to update to a new one? Could be another endpoint or another  HTTP method for  `/register` (i.e. `PUT` instead of `POST`).

> At any rate, if `register/` doesn't send anything more it's going to be nigh impossible to know what customer it is without send some more details, surely? I'd have though minimum would be `org name` and `site name`? This is going by my presumption that a sussoler should do some admin and "approve" a new site (and assign to a customer), which is lacking from the `register/` diagram.

Think answered above re. adding the rego data with the `POST` to the `/registration` endpoint?
> 
> Side note: Sometimes sites are taken down. Is there going to be a way to know this on the infoHub (i.e. for billing purposes)?
> 
> > Main question to be resolved is how to store the client-side secret:
> > 
> > 1. Client certificate encoded into all mSupply instances.
> > 2. Hardcoded global credential.
> > 3. Inject global credential into datafiles (hard to do without hardcoding into update code?).
> 
> If it's a global credential I guess just hardcode it. Though using a pref might be more future proof (even if still hardcoded) as we could adapt it for site credential later if deemed necessary.
> 
> Speaking of secrets, should this repo be public?
> 
> @andreievg I don't know the current code so much. From what I know previously the current/old approach had a hardcoded JWT and the infoHub check against its internally identically hardcoded JWT. For lack of a traditional sort of login/ or register/ end points seems equivalent though.

**Comment by wlthomson** [comment]
There's been a lot of back and forwards discussion, but just to move things along, so I can start coding:

1. I'm going to revert to JWT, but replace the "init" token with a hardcoded secret (for now).
2. To connect a site, `POST` to `/site` with secret. Unregistered sites can be handled in v2 (I think discussion has shown there are a few ways to do this which are compatible).
3. On successful connection, hub responds with JWT signed using public key, which includes the `siteId` and `machineId`. 
4. To log events, `POST` to `/event` with JWT issued on connection.

This is pretty much the original implementation, with a few tweaks. Can I get a sign off on this for the v1 implementation?

@andreievg @Chris-Petty

**Comment by andreievg** [comment]
>  JWT signed using public key 

I hope you mean private secret

> I'm going to revert to JWT, but replace the "init" token with a hardcoded secret (for now).

Ok, but I am still a bit confused, it seems there is a deadline that needs to be met and you would like to get coding. Why would you want to change existing implementation (more time spend coding), if existing way fulfils the task and works ? 

> This is pretty much the original implementation, with a few tweaks. Can I get a sign off on this for the v1 implementation?

I am happy with the way you've described it, as always, the less work/changes the better from my perspective.

**Comment by wlthomson** [comment]
> 
> 
> > JWT signed using public key
> 
> I hope you mean private secret

Yup, private secret from public key!

> > I'm going to revert to JWT, but replace the "init" token with a hardcoded secret (for now).
> 
> Ok, but I am still a bit confused, it seems there is a deadline that needs to be met and you would like to get coding. Why would you want to change existing implementation (more time spend coding), if existing way fulfils the task and works ?

Due to the confusion, I've already done some work down this path, so reverting it back to the original implementation would actually be more work at this stage :(. 

> > This is pretty much the original implementation, with a few tweaks. Can I get a sign off on this for the v1 implementation?
> 
> I am happy with the way you've described it, as always, the less work/changes the better from my perspective.

OK, awesome!

**Comment by Chris-Petty** [comment]
Just ooooone tweak probably from me (relatively indifferent to secret approach, less work better though). `machineId` probs won't cut it :( if you had 2 copies of a data file on a server and open the wrong one (say someone made a copy as they should when upgrading) they'll start posting events on what isn't the true actively being used datafile. Though I'm a bit backseat driving here let me know if I'm overcooked haha.

**Comment by andreievg** [comment]
> Due to the confusion, I've already done some work down this path, so reverting it back to the original implementation would actually be more work at this stage :(.

Cools

**Comment by andreievg** [comment]
> Yup, private secret from public key!

I am confused, we not encrypting anything with JWT, just signing (and it's all done within NPM package anyways), we just need a long and secure secret

**Comment by wlthomson** [comment]
> 
> 
> > Yup, private secret from public key!
> 
> I am confused, we not encrypting anything with JWT, just signing (and it's all done within NPM package anyways), we just need a long and secure secret

Yeah, can just be a secret! The bonus of using a keypair is that we can verify the signature on the client-side too (i.e. guarantee it's from the hub). But for now a secret works fine.
